### ISSUE TITLE
mrcp-server does not startup udp port 

### ISSUE THREAD

**Issue by xiaopenghaha** [laoyin/java-sip-mrcp#1]
场景: 我需要实现一个mrcp-server,这个服务的作用是用来监听三方话务平台推送的语音流给到我这边，然后mrcp-server再调用百度的asr或者tts来进行语音流的转写。

问题：通过提供的MrcpServerSocket类启动的server三方平台无法调通，server端无法接收到语音流。 

初步分析：根据https://lowbibi.com/mrcp/(mrcp协议图解流程)来看，mrcp-client(三方话务平台)在与mrcp-server建立连接的时候，首先是通过udp的端口进行sip协商，但目前mrcp-server没有启动udp端口，从而无法进行sip协商。需要帮忙看一下问题，万分感谢!

**Comment by laoyin** [comment]
MrcpJavaClient 类，我给了client，处理。   然后整个sip和udp、mrcp实现，client版本是完全ok的。

你想基于我这个实现mrcp-server也是可以的，我提供了mrcp协议，但是目前没有提供server 的sip udp 流程。 

你可以参考我 mrcp-client 代码，自己完善 server的 sip流程。

**Comment by laoyin** [comment]
后续我这边是否推出mrcp-server sip流程，得看大家的关注度，还有我个人时间。

**Comment by laoyin** [comment]
项目提供了 mrcp的所有流程，sip流程，rtp，只需要你讲client的，反向转化为server即可。  目前，本人优先做client相关。

**Comment by laoyin** [comment]
后续会推出 java版本的 sip软电话客户端。

**Comment by laoyin** [comment]
在readme 有server的申请地址，server付费

**Comment by TomYang1985** [comment]
博主，现在的mrcp-server sip流程完善了吗？
